"use client";
import { useEffect, useState, type FormEvent } from 'react';
import Link from '@/components/compat/link';
import {Brand,Icon,Modal,SocialLinks} from '@/components/cordon/shared';
import {sections,labels,claimTypes,initial,createRecord,validateAmount,isWorkspace,pledgeCodes,type Section,type Workspace,type RequestRecord,type RequestStatus,type AssetOption,type WorkspaceNote,type HeldItem} from './model';
import type {Change,StoredNote} from '@/lib/cordon';
import {chainId,env} from '@/lib/env';
import {getAccessToken} from '@/lib/supabase';
import {WalletProvider,useCordonWallet} from '@/lib/wallet';
import {useWorkspaceSync} from './use-workspace-sync';
import {useAssetOptions} from './use-assets';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const explanations:Record<Section,string>={overview:'Every right. One private workspace.',bundles:'Separate the rights. Keep control of the underlying.',encumbrances:'Put claims to work without moving ownership.',settlement:'Every leg together. All settle, or none do.',income:'Income follows the claim. Principal stays independent.',nav:'Prove portfolio value without publishing the holdings.',disclosure:'The right information, shared on your terms.',activity:'A clear record of your workspace.',settings:'Make this workspace yours.'};
const actionNames:Partial<Record<Section,string>>={bundles:'Create bundle',encumbrances:'Create encumbrance',settlement:'Build settlement',income:'Set income term',nav:'Prepare attestation',disclosure:'Create disclosure'};
function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function Empty({title,copy,action,onClick}:{title:string;copy:string;action?:string;onClick?:()=>void}){return <div className="empty-state"><div className="empty-symbol"><Icon name="bundles"/></div><h3>{title}</h3><p>{copy}</p>{action&&<button className="secondary-btn" onClick={onClick}>{action}<Icon name="plus"/></button>}</div>}
export function Dashboard(props:{section?:Section}){return <WalletProvider><DashboardView {...props}/></WalletProvider>}
function DashboardView({section='overview'}:{section?:Section}){
 const [workspace,setWorkspace]=useState<Workspace>(initial),[ready,setReady]=useState(false),[storageError,setStorageError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[modal,setModal]=useState(''),[selected,setSelected]=useState<RequestRecord|null>(null),[toast,setToast]=useState(''),[walletError,setWalletError]=useState(''),[navOpen,setNavOpen]=useState(false);
 const w=useCordonWallet(),wallet=w.address,busy=w.busy,sync=useWorkspaceSync(workspace,setWorkspace,w),assetOptions=useAssetOptions();
 useEffect(()=>{try{const raw=localStorage.getItem('cordon-workspace-v1');if(raw){const data=JSON.parse(raw);if(isWorkspace(data))setWorkspace(data)}else{const name=localStorage.getItem('cordon-workspace-name');if(name)setWorkspace({...initial,name})}}catch{setStorageError('Your browser could not restore the workspace. You can continue and export your work.')}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('cordon-workspace-v1',JSON.stringify(workspace))}catch{setStorageError('Browser storage is unavailable. Export requests to keep a copy.')}},[workspace,ready]);
 useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(id)}},[toast]);
 useEffect(()=>{type MC={registerTool:(t:unknown,o:{signal:AbortSignal})=>void};const context=(document as Document&{modelContext?:MC}).modelContext;if(!context)return;const lifecycle=new AbortController();try{context.registerTool({name:'read_cordon_workspace',description:'Read device-local prepared request counts. No on-chain balances or settlements are reported.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({name:workspace.name,prepared:workspace.requests.filter(r=>r.status==='Prepared').length,section})},{signal:lifecycle.signal});context.registerTool({name:'open_cordon_request_form',description:'Open a request form. Does not sign or submit a transaction.',inputSchema:{type:'object',properties:{module:{type:'string',enum:Object.keys(actionNames)}},required:['module'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{module:string})=>{if(!Object.hasOwn(actionNames,input.module))throw new Error('Unsupported module');setModal(input.module);return {opened:input.module}}},{signal:lifecycle.signal})}catch{}return()=>lifecycle.abort()},[workspace,section]);
 const active=workspace.requests.filter(r=>r.status==='Prepared');const shown=workspace.requests.filter(r=>(section==='activity'||r.kind===section)&&(filter==='All'||r.status===filter)&&`${r.name} ${r.asset} ${r.kind}`.toLowerCase().includes(query.toLowerCase()));
 function save(r:RequestRecord){setWorkspace(w=>({...w,requests:[r,...w.requests]}));setModal('');setToast('Request prepared and saved to this workspace.')}function archive(r:RequestRecord){setWorkspace(w=>({...w,requests:w.requests.map(x=>x.id===r.id?{...x,status:x.status==='Archived'?'Prepared':'Archived'}:x)}));setSelected(null);setToast(r.status==='Archived'?'Request restored.':'Request archived.');}
 const onChain=Boolean(env.deployment);
 const notes=(workspace.notes??[]) as unknown as StoredNote[],[noteBusy,setNoteBusy]=useState('');
 /** Merge an action's result: new notes replace any pending copy, spent ones are marked. */
 const keep=(ch:Change)=>setWorkspace(ws=>{const add=new Map(ch.add.map(n=>[n.commit,n as WorkspaceNote]));return{...ws,notes:[...(ws.notes??[]).filter(n=>!add.has(n.commit)).map(n=>ch.spent.includes(n.commit)?{...n,status:'spent' as const}:n),...add.values()]}});
 const drop=(commits:string[])=>setWorkspace(ws=>({...ws,notes:(ws.notes??[]).filter(n=>!commits.includes(n.commit))}));
 const pendingNotes=notes.filter(n=>n.status==='pending').length;
 useEffect(()=>{if(!onChain||!pendingNotes)return;let live=true;import('@/lib/cordon').then(c=>c.indexed(notes)).then(ids=>{if(live&&ids.length)setWorkspace(ws=>({...ws,notes:(ws.notes??[]).map(n=>n.status==='pending'&&ids.includes(n.commit)?{...n,status:'live' as const}:n)}))}).catch(()=>{});return()=>{live=false}},[section,pendingNotes]);// eslint-disable-line react-hooks/exhaustive-deps
 const setReq=(id:string,status:RequestStatus,extra:Partial<RequestRecord>={})=>setWorkspace(ws=>({...ws,requests:ws.requests.map(x=>x.id===id?{...x,status,...extra}:x)}));
 const assetByName=(name:string)=>assetOptions.find(o=>o.name===name)??assetOptions.find(o=>o.name.startsWith(name));
 /** Bundles: deposit then bundle, or recombine. Income: term (and send it). Encumbrances, settlement orders, disclosures. */
 async function submitOnChain(r:RequestRecord){setSelected(null);const setStatus=(status:RequestStatus,extra:Partial<RequestRecord>={})=>setReq(r.id,status,extra);
  const h={step:(s:RequestStatus)=>setStatus(s),keep,drop};
  try{const c=await import('@/lib/cordon');const live=notes.filter(n=>n.status==='live'&&n.lock==='0');let res:Change,done:string;
   if(r.kind==='settlement'){const legs=JSON.parse(r.details.legs_json??'[]') as {side:string;asset:string;amount:string}[];const give=legs.filter(l=>l.side==='Deliver'),want=legs.filter(l=>l.side==='Receive');const g=[...new Set(give.map(l=>l.asset))],v=[...new Set(want.map(l=>l.asset))];
    if(g.length!==1||v.length!==1)throw new Error('On-chain settlement trades one asset for another: deliver one asset and receive one asset.');const go=assetByName(g[0]),wo=assetByName(v[0]);if(!go?.address||!wo?.address)throw new Error('Both assets must be registered on-chain.');
    const order=await c.placeOrder({notes,give:go.address as `0x${string}`,raw:give.reduce((s,l)=>s+BigInt(Math.floor(Number(l.amount))),0n),want:wo.address as `0x${string}`,ref:r.id});setStatus('Submitted',{error:undefined,details:{...r.details,order}});setToast('Order sealed and queued. It settles in the next batch with a matching order; the result arrives in your inbox, or is rebuilt from the chain.');return}
   if(r.kind==='disclosure'){if(!(await getAccessToken())){await sync.start();if(!(await getAccessToken()))throw new Error('Sign in with your wallet (Sync workspace) to share a disclosure.')}
    const pick=r.details.scope==='Portfolio'?live:r.details.scope==='Bundle'?live.filter(n=>n.bundleId===r.details.target):live.filter(n=>n.commit===r.details.target);if(!pick.length)throw new Error('Nothing in this workspace matches that scope.');
    const id=await c.grantDisclosure({to:r.details.recipient,scope:r.details.scope,purpose:r.details.purpose,until:r.details.until,notes:pick});const link=`${location.origin}/dashboard/disclosure?view=${id}`;
    setStatus('Confirmed',{details:{...r.details,grant:id,link}});void navigator.clipboard?.writeText(link).catch(()=>{});setToast('Disclosure shared. The link is copied; send it to the recipient.');return}
   const option=assetOptions.find(o=>o.name===r.asset);if(!option?.address)throw new Error('This asset is not registered on-chain yet.');const asset=BigInt(option.address).toString(),mine=live.filter(n=>n.asset===asset);
   if(r.kind==='bundles'&&r.details.operation==='Recombine claims'){const p=mine.find(n=>n.kind==='1');if(!p)throw new Error(`No free ${r.asset} bundle in this workspace.`);res=await c.unbundle(notes,p.bundleId,h);done='Claims recombined into the underlying.'}
   else if(r.kind==='bundles'){const raw=BigInt(Math.floor(r.amount));const note=notes.find(n=>n.status!=='spent'&&n.asset===asset&&n.kind==='0'&&n.lock==='0'&&n.raw===raw.toString());
    if(!note){setStatus('Submitted');const stored=await c.deposit(option.address as `0x${string}`,raw);keep({tx:null,spent:[],add:[stored]});setStatus('Prepared');setToast('Deposited. After the 15-minute standby, submit again to bundle.');return}
    res=await c.bundle(note,h);done='Bundle settled. Your claim notes are in this workspace.'}
   else if(r.kind==='income'){const n=mine.find(n=>n.kind==='2'&&n.termFrom==='0'&&n.termUntil==='0');if(!n)throw new Error(`No open-ended ${r.asset} INCOME claim in this workspace. Bundle first.`);res=await c.setIncomeTerm(n,BigInt(Math.floor(Date.now()/1000)+parseInt(r.details.term)*30*86400),h);done='Income term set. The termed income and its remainder are in this workspace.';
    const to=r.details.recipient?.trim();const termed=res.add.find(x=>x.termUntil!=='0');if(to&&termed){keep(res);res=await c.send(termed,BigInt(termed.raw),to,h);done='Income term set and sent to the recipient. The remainder returns to you at the end of the term.'}}
   else{const kind=String(claimTypes.indexOf(r.details.claim)+1);const n=mine.find(n=>n.kind===kind&&n.termUntil==='0');if(!n)throw new Error(`No free ${r.asset} ${r.details.claim} claim in this workspace.`);const type=r.details.type as 'LOCKUP'|'PLEDGE'|'LIEN';
    res=await c.encumber(n,{kind:type,until:BigInt(Math.floor(new Date(r.details.until).getTime()/1000)),holder:r.details.holder,obligation:r.details.obligation},h);done=type==='LOCKUP'?`Locked until ${r.details.until}.`:`${type} created. The holder received the terms in their inbox; only they can release it.`}
   keep(res);setStatus('Confirmed',{tx:res.tx??undefined,error:undefined});setToast(done)}
  catch(e){setStatus('Failed',{error:(e as Error).message});setToast((e as Error).message)}}
 async function revoke(r:RequestRecord){try{const c=await import('@/lib/cordon');await c.revokeDisclosure(r.details.grant);setReq(r.id,'Archived',{details:{...r.details,revoked:'yes'}});setSelected(null);setToast('Disclosure revoked. The link no longer opens.')}catch(e){setToast((e as Error).message)}}
 const [withdrawing,setWithdrawing]=useState<StoredNote|null>(null);
 async function noteAction(n:StoredNote,act:NoteAct,raw?:string){setWithdrawing(null);setNoteBusy(n.commit);try{const c=await import('@/lib/cordon');const h={keep,drop};const res=act==='withdraw'?await c.withdraw(n,wallet as `0x${string}`,h,raw==='whole'?'whole':BigInt(raw??'')):act==='claim'?await c.claimIncome(n,h):act==='recombine'?await c.unbundle(notes,n.bundleId,h):await c.unlock(n,h);keep(res);setToast(res.message??noteDone[act])}catch(e){setToast((e as Error).message)}finally{setNoteBusy('')}}
 const [sending,setSending]=useState<StoredNote|null>(null);
 async function sendNote(n:StoredNote,raw:string,to:string){setSending(null);setNoteBusy(n.commit);try{const c=await import('@/lib/cordon');keep(await c.send(n,BigInt(raw),to,{keep,drop}));setToast('Sent. The recipient sees it after checking their inbox.')}catch(e){setToast((e as Error).message)}finally{setNoteBusy('')}}
 /** Opens new inbox boxes: received notes, encumbrances held for others, DvP results for this workspace's orders. */
 async function checkInbox(quiet=false){try{const c=await import('@/lib/cordon');const {cursor,items}=await c.readInbox(workspace.inbox??0);let count=0;
  const codeFree=pledgeCodes(workspace.held??[]);
  for(const it of items){if(it.t==='notes'&&it.add.length){keep({tx:null,spent:[],add:it.add});count+=it.add.length}
   else if(it.t==='held'){// A pledge code is single-use: a second encumbrance on the same code shares its release secret.
    if(!codeFree(it)){setToast('A borrower reused one of your pledge codes; that pledge is not safe and was not added.');continue}
    const item:HeldItem={enc:it.enc,locked:it.locked as WorkspaceNote,nonce:it.nonce,state:'pending'};setWorkspace(ws=>({...ws,held:[...(ws.held??[]).filter(x=>x.enc!==it.enc),item]}));count++}
   // DvP results are rebuilt from the chain below (recoverOrder); an inbox item only says "look now".
   else if(it.t==='dvp')count++}
  for(const r of workspace.requests.filter(r=>r.kind==='settlement'&&r.status==='Submitted'&&r.details.order)){const got=await c.recoverOrder(r.details.order).catch(()=>null);if(!got)continue;if(got.expired)setReq(r.id,'Failed',{error:'The order expired without a match.'});else{keep(got);setReq(r.id,'Confirmed',{tx:got.tx??undefined,error:undefined});count++}}
  setWorkspace(ws=>({...ws,inbox:Math.max(ws.inbox??0,cursor)}));if(!quiet||count)setToast(count?`${count} new item${count>1?'s':''} from your inbox.`:'Nothing new in your inbox.')}catch(e){if(!quiet)setToast((e as Error).message)}}
 useEffect(()=>{if(!onChain||!wallet)return;const id=setInterval(()=>{void import('@/lib/cordon').then(c=>{if(c.keyReady())void checkInbox(true)})},30000);return()=>clearInterval(id)});
 const held=workspace.held??[];
 const setHeld=(enc:string,state:HeldItem['state'])=>setWorkspace(ws=>({...ws,held:(ws.held??[]).map(x=>x.enc===enc?{...x,state}:x)}));
 useEffect(()=>{if(section!=='encumbrances'||!onChain||!held.length)return;void import('@/lib/cordon').then(async c=>{for(const x of held)setHeld(x.enc,await c.heldState(x as never).catch(()=>x.state))})},[section,held.length]);// eslint-disable-line react-hooks/exhaustive-deps
 async function heldAction(x:HeldItem,act:'release'|'default'|'enforce'){setNoteBusy(x.enc);try{const c=await import('@/lib/cordon');const item=x as never;
  if(act==='release'){await c.release(item,{});setHeld(x.enc,'released');setToast('Released. The owner can unlock the note.')}
  else if(act==='default'){await c.requestDefault(item);setToast('Default requested. Once the keeper declares it (about a minute), enforce.')}
  else{keep(await c.enforce(item,{keep,drop}));setHeld(x.enc,'enforced');setToast('Enforced. The note is yours now.')}}catch(e){setToast((e as Error).message)}finally{setNoteBusy('')}}
 async function connect(target?:Parameters<typeof w.connect>[0]){setWalletError('');try{await w.connect(target);setModal('');setToast('Wallet connected. No transaction has been requested.')}catch(e){setWalletError((e as Error).message||'Wallet connection was declined.')}}
 function exportRequests(){const rows=[['Name','Module','Asset','Amount','Status','Created'],...workspace.requests.map(r=>[r.name,labels[r.kind as Section]||r.kind,r.asset,String(r.amount),r.status,r.created])];download('cordon-activity.csv',rows.map(row=>row.map(v=>'"'+v.replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\n'),'text/csv');setToast('Activity exported.')}
 return <div className="dashboard-shell"><aside className={'dash-sidebar '+(navOpen?'open':'')}><Brand/><div className="workspace-switch"><span className="workspace-avatar">{workspace.name.slice(0,1).toUpperCase()}</span><div><strong>{workspace.name}</strong><small>Personal workspace</small></div></div><p className="nav-group-label">WORKSPACE</p><nav aria-label="Dashboard">{sections.map((s,i)=><Link key={s} href={s==='overview'?'/dashboard':`/dashboard/${s}`} aria-current={section===s?'page':undefined} onClick={()=>setNavOpen(false)} className={section===s?'active':''}><Icon name={s}/><span>{labels[s]}</span>{i===1&&active.filter(r=>r.kind==='bundles').length>0&&<em>{active.filter(r=>r.kind==='bundles').length}</em>}</Link>)}</nav><div className="nav-soon" aria-disabled="true" title="$CRDN has not launched yet"><Icon name="income"/><span>$CRDN staking</span><em>Coming soon</em></div><div className="sidebar-bottom"><div className="privacy-card"><Icon name="encumbrances"/><strong>Behind the cordon.</strong><p>Confidential. Provable.<br/>Disclosable.</p><Link href="/docs">Read the documentation ↗</Link></div><SocialLinks compact/><Link href="/" className="back-home">← Back to website</Link></div></aside>{navOpen&&<button className="sidebar-scrim" aria-label="Close navigation" onClick={()=>setNavOpen(false)}/>}
 <div className="dash-main"><header className="dash-header"><button className="icon-btn mobile-nav" aria-label="Open navigation" onClick={()=>setNavOpen(true)}>☰</button><div className="breadcrumbs">Workspace <span>/</span> <strong>{labels[section]}</strong></div><div className="header-actions"><span className="network-chip">Robinhood Chain</span><button className="secondary-btn wallet-btn" onClick={()=>setModal('wallet')}><Icon name="wallet"/>{wallet?wallet.slice(0,6)+'…'+wallet.slice(-4):'Connect wallet'}</button></div></header>
  <main key={section} className="dash-content dash-page-enter"><div className="page-heading"><div><p className="eyebrow">CORDON / {section==='overview'?'ASSET SERVICING':labels[section].toUpperCase()}</p><h1>{labels[section]}</h1><p>{explanations[section]}</p></div><div className="page-actions">{section==='overview'?<><button className="icon-btn" aria-label={workspace.hideValues?'Show values':'Hide values'} onClick={()=>setWorkspace(w=>({...w,hideValues:!w.hideValues}))}><Icon name="disclosure"/></button><button className="primary-btn" onClick={()=>setModal('bundles')}><Icon name="plus"/>Create bundle</button></>:actionNames[section]?<button className="primary-btn" onClick={()=>setModal(section)}><Icon name="plus"/>{actionNames[section]}</button>:section==='activity'?<button className="secondary-btn" onClick={exportRequests}><Icon name="download"/>Export CSV</button>:null}</div></div>
 {storageError&&<p role="alert" className="notice">{storageError}</p>}
 {section==='overview'?<><div className="metric-grid">{[['Prepared requests',active.length,'Ready for your review'],['Rights bundles',active.filter(r=>r.kind==='bundles').length,'Five claim types per stock bundle'],['Settlement legs',active.filter(r=>r.kind==='settlement').reduce((sum,r)=>sum+Number(r.details.legs||0),0),'Atomic by design'],['Disclosures',active.filter(r=>r.kind==='disclosure').length,'Scoped access requests']].map(([name,val,caption])=><div className="metric-card" key={String(name)}><span>{name}</span><strong>{workspace.hideValues?'••••':val}</strong><small>{caption}</small></div>)}</div>
 <div className="overview-grid"><section className="dash-card portfolio-card"><div className="card-heading"><h2>Your asset workspace</h2><span className="tag">Private by default</span></div><div className="portfolio-visual"><div className="portfolio-orbit"><img src="/brand/cordon-symbol.png" alt="Cordon"/></div><div><span className="eyebrow">ONE UNDERLYING. FIVE RIGHTS.</span><h3>More possibilities.<br/><i>The same asset.</i></h3><p>Prepare a rights bundle, direct your income, or structure an atomic exchange.</p><Link href="/dashboard/bundles" className="text-link">Explore your rights <Icon name="arrow"/></Link></div></div><div className="claim-legend">{claimTypes.map((c,i)=><span key={c}><b style={{background:['#ff8158','#ffad75','#ffc99a','#c68765','#87563f'][i]}}/>{c}</span>)}</div></section><section className="dash-card quick-actions"><div className="card-heading"><h2>Quick actions</h2><span className="muted">01 — 05</span></div>{(['bundles','encumbrances','settlement','income','nav'] as Section[]).map(s=><button key={s} onClick={()=>setModal(s)}><span className="quick-icon"><Icon name={s}/></span><span><strong>{actionNames[s]}</strong><small>{s==='bundles'?'Separate rights from underlying':s==='encumbrances'?'Pledges, liens, and lockups':s==='settlement'?'Compose up to 16 legs':s==='income'?'Time-bound income claims':'Calculate a portfolio valuation'}</small></span><Icon name="arrow"/></button>)}</section></div>
 {onChain&&(!!wallet||notes.some(n=>n.status!=='spent'))&&<PrivateNotes notes={notes} options={assetOptions} hide={workspace.hideValues} busy={noteBusy} canAct={!!wallet} onAction={(n,a)=>a==='withdraw'?setWithdrawing(n):void noteAction(n,a)} onSend={setSending} onInbox={()=>void checkInbox()}/>}<section className="dash-card"><div className="card-heading"><h2>Recent activity</h2><Link href="/dashboard/activity" className="text-link">View all <Icon name="arrow"/></Link></div>{workspace.requests.length?<Records records={workspace.requests.slice(0,5)} onSelect={setSelected} hide={workspace.hideValues}/>:<Empty title="Your workspace starts here" copy="Prepare your first bundle to begin organizing your asset rights." action="Create a bundle" onClick={()=>setModal('bundles')}/>}</section><div className="protocol-strip"><span><Icon name="encumbrances"/>Holdings stay confidential</span><span>5 claim types</span><span>16 settlement legs</span><Link href="/docs">Explore the protocol ↗</Link></div></>:
 section==='settings'?<><Settings workspace={workspace} update={setWorkspace} notify={setToast}/>{onChain&&<CordonKeyCard wallet={wallet} notify={setToast}/>}{chainId===46630&&onChain&&<TestFaucet wallet={wallet} notify={setToast}/>}</>:
 <>{section==='bundles'&&<div className="rights-grid">{claimTypes.map((c,i)=><div key={c} className="right-card"><span>0{i+1}</span><Icon name={i===1?'income':'bundles'}/><h3>{c}</h3><p>{['The underlying asset','The dividend stream','Governance, where applicable','The redemption right','Permission to re-bundle'][i]}</p></div>)}</div>}
 {section==='encumbrances'&&<ModuleIntro items={[['Lockup','Prevent transfer until a specified time.'],['Pledge','Bind a claim to an obligation.'],['Lien','Define an obligation and a recovery waterfall.']]}/>}
 {section==='encumbrances'&&onChain&&held.length>0&&<HeldCard held={held} options={assetOptions} busy={noteBusy} canAct={!!wallet} onAction={(x,a)=>void heldAction(x,a)}/>}
 {section==='settlement'&&<ModuleIntro items={[['Up to 16 legs','Compose asset-for-asset or claim-for-claim exchanges.'],['All or nothing','The complete exchange settles atomically.'],['60-second batches','Sealed matching with oracle-guarded marks.']]}/>}
 {section==='income'&&<ModuleIntro items={[['Time-bound income','Set a term for the INCOME claim.'],['Multiplier-aware','Accrual follows the underlying asset’s income index.'],['Principal preserved','Income rights are tracked separately from principal.']]}/>}
 {section==='nav'&&onChain&&<VaultCard wallet={wallet} notes={notes} notify={setToast} signIn={()=>sync.start()}/>}
 {section==='nav'&&<NavCalculator onSave={save}/>}
 {section==='disclosure'&&<ModuleIntro items={[['Claim','Limit visibility to one specific right.'],['Bundle','Share the related claims of one underlying.'],['Portfolio','Prepare a complete portfolio disclosure.']]}/>}
 {section==='disclosure'&&onChain&&<DisclosureViewer wallet={wallet} options={assetOptions}/>}
 <section className="dash-card"><div className="card-heading"><h2>{section==='activity'?'Workspace history':`${labels[section]} requests`}</h2><span className="tag">{shown.length} records</span></div><div className="table-toolbar"><label className="search-field"><Icon name="search"/><input aria-label="Search requests" placeholder="Search name or asset…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Filter requests" value={filter} onChange={e=>setFilter(e.target.value)}>{['All','Prepared','Confirmed','Failed','Archived'].map(f=><option key={f}>{f}</option>)}</select></div>{shown.length?<Records records={shown} onSelect={setSelected} hide={workspace.hideValues}/>:<Empty title={query||filter!=='All'?'No matching requests':'No requests yet'} copy={query||filter!=='All'?'Try a different search or status.':'Prepared requests appear here, ready for your review.'} action={actionNames[section]} onClick={()=>setModal(section)}/>}</section></>}
 <footer className="dash-footer"><span>© 2026 Cordon</span><span>{sync.state==='synced'?'Workspace encrypted and synced to your wallet.':'Workspace requests are stored on this device.'}</span><Link href="/docs">Documentation ↗</Link></footer></main></div>
 {modal==='wallet'&&<Modal title={wallet?'Connected wallet':'Connect your wallet'} onClose={()=>setModal('')}><div className="wallet-illustration"><Icon name="wallet"/></div><p>{wallet||'Use your wallet to identify your account.'}</p><p className="muted">You stay in control. Connecting does not request a signature or move assets.</p>{walletError&&<p className="form-error" role="alert">{walletError}</p>}{wallet?<button className="secondary-btn" onClick={()=>{w.disconnect();void sync.stop();setModal('');setToast('Wallet disconnected from this workspace.')}}>Disconnect</button>:w.choices.length>1?w.choices.map(c=><button key={c.uid} className="primary-btn" disabled={busy} onClick={()=>connect(c)}>{busy?'Connecting…':c.name}<Icon name="arrow"/></button>):<button className="primary-btn" disabled={busy} onClick={()=>connect()}>{busy?'Connecting…':'Browser wallet'}<Icon name="arrow"/></button>}
 {wallet&&sync.available&&<><div className="settings-divider"/><h3>Encrypted sync</h3><p className="muted">{sync.state==='synced'?'Your workspace is encrypted in this browser and synced to this wallet.':'Keep your workspace on every device. It is encrypted in this browser first. You sign twice: once to sign in, once to derive your key. Neither moves assets.'}</p>{sync.error&&<p className="form-error" role="alert">{sync.error}</p>}{sync.state==='synced'?<button className="secondary-btn" onClick={()=>{void sync.stop();setToast('Sync stopped. Your workspace stays on this device.')}}>Stop syncing</button>:<button className="primary-btn" disabled={sync.state==='working'} onClick={()=>void sync.start()}>{sync.state==='working'?'Waiting for your wallet…':'Sync workspace'}<Icon name="arrow"/></button>}</>}</Modal>}
 {modal&&modal!=='wallet'&&<RequestForm kind={modal as Section} onSave={save} onClose={()=>setModal('')} requests={active} options={assetOptions} notes={notes.filter(n=>n.status==='live'&&n.lock==='0')}/>}
 {sending&&<SendModal note={sending} onClose={()=>setSending(null)} onSend={(raw,to)=>void sendNote(sending,raw,to)}/>}
 {withdrawing&&<WithdrawModal note={withdrawing} onClose={()=>setWithdrawing(null)} onWithdraw={raw=>void noteAction(withdrawing,'withdraw',raw)}/>}
 {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)}><p className="muted">{labels[selected.kind as Section]} · {selected.status}</p><dl className="detail-list"><div><dt>Asset</dt><dd>{selected.asset}</dd></div><div><dt>Amount</dt><dd>{workspace.hideValues?'••••':selected.amount.toLocaleString()}</dd></div>{Object.entries(selected.details).filter(([k])=>!['name','amount','asset','legs_json','grant'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{v}</dd></div>)}<div><dt>Created</dt><dd>{new Date(selected.created).toLocaleString()}</dd></div></dl><p className="small muted">{selected.status==='Confirmed'?`Settled on Robinhood Chain${selected.tx?` · ${selected.tx.slice(0,10)}…`:''}.`:selected.status==='Failed'?selected.error||'The last submission failed.':selected.status==='Proving'||selected.status==='Submitted'?'Submission in progress.':'Prepared for review. This request has not been submitted to the network.'}</p><div className="form-actions"><button className="secondary-btn" onClick={()=>archive(selected)}>{selected.status==='Archived'?'Restore':'Archive'}</button>{onChain&&['bundles','income','encumbrances','settlement','disclosure'].includes(selected.kind)&&(selected.status==='Prepared'||selected.status==='Failed')&&<button className="primary-btn" disabled={!wallet} onClick={()=>void submitOnChain(selected)}>{selected.kind==='disclosure'?'Share':'Submit on-chain'}<Icon name="arrow"/></button>}{selected.kind==='disclosure'&&selected.details.grant&&selected.status==='Confirmed'&&<button className="secondary-btn" onClick={()=>void revoke(selected)}>Revoke</button>}<button className="primary-btn" onClick={()=>{download(`cordon-${selected.id}.json`,JSON.stringify(selected,null,2));setToast('Request exported.')}}><Icon name="download"/>Export request</button></div></Modal>}
 {toast&&<div role="status" className="cordon-toast"><Icon name="check"/>{toast}</div>}
 </div>
}
function Records({records,onSelect,hide}:{records:RequestRecord[];onSelect:(r:RequestRecord)=>void;hide:boolean}){return <div className="table-scroll"><table className="records-table"><thead><tr><th>Request</th><th>Asset / scope</th><th>Amount</th><th>Status</th><th>Created</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td><button onClick={()=>onSelect(r)} className="record-title"><span className="record-icon"><Icon name={r.kind}/></span><span><strong>{r.name}</strong><small>{labels[r.kind as Section]}</small></span></button></td><td>{r.asset}</td><td className="mono">{hide?'••••':r.amount.toLocaleString()}</td><td><span className={'status-tag '+r.status.toLowerCase()}>{r.status}</span></td><td>{new Date(r.created).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</td><td><button className="icon-btn" aria-label={`View ${r.name}`} onClick={()=>onSelect(r)}><Icon name="arrow"/></button></td></tr>)}</tbody></table></div>}
function ModuleIntro({items}:{items:[string,string][]}){return <div className="module-intro">{items.map(([title,copy],i)=><div key={title}><span className="eyebrow">0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</div>}
function RequestForm({kind,onSave,onClose,requests,options,notes}:{kind:Section;onSave:(r:RequestRecord)=>void;onClose:()=>void;requests:RequestRecord[];options:AssetOption[];notes:StoredNote[]}){
 const [scope,setScope]=useState('Claim'),[type,setType]=useState('LOCKUP'),[error,setError]=useState(''),[amount,setAmount]=useState('100'),[asset,setAsset]=useState(options[0].name),[legs,setLegs]=useState([{asset:options[0].name,amount:'100',side:'Deliver'},{asset:'USDG',amount:'100',side:'Receive'}]);
 const claims=(options.find(o=>o.name===asset)??options[0]).claims;
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');try{const fields=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;if(kind==='settlement'){if(legs.length<2||legs.length>16)throw new Error('An atomic settlement needs 2 to 16 legs.');if(!legs.some(l=>l.side==='Deliver')||!legs.some(l=>l.side==='Receive'))throw new Error('Include both a delivery and a receipt.');legs.forEach(l=>validateAmount(l.amount));fields.legs=String(legs.length);fields.composition=legs.map(l=>`${l.side} ${l.amount} ${l.asset}`).join(' · ');fields.amount=String(legs.length);fields.asset='Multi-asset';fields.legs_json=JSON.stringify(legs);}if(kind==='disclosure'&&!isCordonKey(fields.recipient))throw new Error('Enter the recipient’s Cordon key (0x followed by 128 hex characters).');if(kind==='disclosure'&&fields.scope!=='Portfolio'&&!fields.target)throw new Error('Choose what to disclose.');if(kind==='encumbrances'&&fields.type!=='LOCKUP'&&!isPledgeCode(fields.holder))throw new Error('Enter the holder’s pledge code (0x followed by 256 hex characters) for a pledge or lien.');if(kind==='income'&&fields.recipient&&!isCordonKey(fields.recipient))throw new Error('Enter the recipient’s Cordon key, or leave it empty.');onSave(createRecord(kind,fields))}catch(e){setError((e as Error).message)}}
 return <Modal title={actionNames[kind]||'Prepare request'} onClose={onClose}><p className="muted">{explanations[kind]}</p><form onSubmit={submit} className="request-form"><label>Request name<input name="name" placeholder={kind==='bundles'?'My NVDA bundle':'Name this request'} required maxLength={80}/></label>
 {kind==='settlement'?<div className="settlement-legs">{legs.map((leg,i)=><div className="settlement-leg" key={i}><span className="eyebrow">LEG {String(i+1).padStart(2,'0')}</span><div><select aria-label={`Leg ${i+1} direction`} value={leg.side} onChange={e=>setLegs(ls=>ls.map((l,j)=>j===i?{...l,side:e.target.value}:l))}><option>Deliver</option><option>Receive</option></select><select aria-label={`Leg ${i+1} asset`} value={leg.asset} onChange={e=>setLegs(ls=>ls.map((l,j)=>j===i?{...l,asset:e.target.value}:l))}>{[...options.map(o=>o.name),...(options.some(o=>o.name.startsWith('USDG'))?[]:['USDG'])].map(a=><option key={a}>{a}</option>)}</select><input aria-label={`Leg ${i+1} amount`} type="number" min="0.000001" step="any" required value={leg.amount} onChange={e=>setLegs(ls=>ls.map((l,j)=>j===i?{...l,amount:e.target.value}:l))}/><button type="button" className="icon-btn" aria-label={`Remove leg ${i+1}`} disabled={legs.length<=2} onClick={()=>setLegs(ls=>ls.filter((_,j)=>j!==i))}><Icon name="close"/></button></div></div>)}<button type="button" className="secondary-btn" disabled={legs.length>=16} onClick={()=>setLegs(ls=>[...ls,{asset:'USDG',amount:'1',side:'Receive'}])}><Icon name="plus"/>Add leg ({legs.length}/16)</button><p className="small muted">5 bps per leg. On-chain orders deliver one asset for another at the batch’s oracle prices (within 0.25%); amounts are raw units.</p></div>:
 kind==='disclosure'?<><label>Disclosure scope<select name="scope" value={scope} onChange={e=>setScope(e.target.value)}><option>Claim</option><option>Bundle</option><option>Portfolio</option></select></label>{scope!=='Portfolio'&&<label>{scope==='Claim'?'Note':'Bundle'}<select name="target">{scope==='Claim'?notes.map(n=>{const o=options.find(x=>x.address&&BigInt(x.address).toString()===n.asset);return <option key={n.commit} value={n.commit}>{o?.name??'Asset'} · {['UNDERLYING',...claimTypes][Number(n.kind)]} · {n.raw}</option>}):[...new Set(notes.filter(n=>n.bundleId!=='0').map(n=>n.bundleId))].map(b=><option key={b} value={b}>Bundle {b.slice(0,8)}…</option>)}</select></label>}<label>Recipient’s Cordon key<input name="recipient" required placeholder="0x… (Settings → Your Cordon key)" maxLength={200}/></label><label>Purpose<input name="purpose" required placeholder="Portfolio review" maxLength={200}/></label><input type="hidden" name="amount" value="1"/><label>Expires on<input type="date" name="until" required min={new Date(Date.now()+86400000).toISOString().slice(0,10)}/></label></>:
 <><div className="form-row"><label>Asset<select name="asset" value={asset} onChange={e=>setAsset(e.target.value)}>{options.map(o=><option key={o.name}>{o.name}</option>)}</select></label><label>{kind==='nav'?'Declared NAV (USDG)':'Raw units'}<input name="amount" type="number" min="0.000001" max="1000000000000" step="any" required value={amount} onChange={e=>setAmount(e.target.value)}/></label></div>
 {kind==='bundles'&&<><label>Bundle operation<select name="operation"><option>Bundle underlying</option><option>Recombine claims</option></select></label><div className="form-claims">{claims.map(c=><span key={c}>{c}</span>)}</div><div className="form-summary"><span>Servicing fee</span><strong>10 bps · 0.10%</strong></div><p className="small muted">A new deposit passes screening and a 15-minute standby. Recombining requires the full applicable claim set without active encumbrances.</p></>}
 {kind==='encumbrances'&&<><div className="form-row"><label>Type<select name="type" value={type} onChange={e=>setType(e.target.value)}><option>LOCKUP</option><option>PLEDGE</option><option>LIEN</option></select></label><label>Claim<select name="claim">{claims.map(c=><option key={c}>{c}</option>)}</select></label></div><label>Obligation / condition<input name="obligation" required placeholder="Describe the obligation or release condition" maxLength={250}/></label>{type!=='LOCKUP'&&<label>Holder’s pledge code<input name="holder" required placeholder="0x… (the holder’s Settings → New pledge code)" maxLength={300}/></label>}<label>Until<input type="date" name="until" required min={new Date(Date.now()+86400000).toISOString().slice(0,10)}/></label><p className="small muted">{type==='LOCKUP'?'The claim stays yours and unlocks on the end date.':'The holder receives the terms. Only the holder can release it when the obligation is met, or take the claim after a declared default.'}</p></>}
 {kind==='income'&&<><label>Income term<select name="term"><option>3 months</option><option>6 months</option><option>12 months</option><option>24 months</option></select></label><label>Income recipient (optional)<input name="recipient" placeholder="Recipient’s Cordon key, or empty to keep it" maxLength={200}/></label><p className="small muted">Income accrues to the INCOME claim. The term reverts to the bundle owner on expiry.</p></>}
 {kind==='nav'&&<><label>Vault / basket identifier<input name="vault" required placeholder="Name or identifier" maxLength={100}/></label><label>Epoch cadence<select name="cadence"><option>Hourly</option><option>Daily</option></select></label><p className="small muted">The attestation request records your declared NAV. A valid proof requires verified holdings, liabilities, and oracle marks.</p></>}
 </>}
 {requests.some(r=>r.kind==='bundles')&&kind==='encumbrances'&&<label>Reference bundle<select name="reference"><option value="">Select a prepared bundle</option>{requests.filter(r=>r.kind==='bundles').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>}
 {error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button type="submit" className="primary-btn">Prepare request<Icon name="arrow"/></button></div><p className="small muted">Saved on this device for review. No assets move at this step.</p></form></Modal>
}
function NavCalculator({onSave}:{onSave:(r:RequestRecord)=>void}){const [units,setUnits]=useState('100'),[price,setPrice]=useState('0'),[multiplier,setMultiplier]=useState('1'),[liabilities,setLiabilities]=useState('0'),[shares,setShares]=useState('100'),[error,setError]=useState('');const gross=Number(units)*Number(price)*Number(multiplier),net=gross-Number(liabilities),perShare=Number(shares)>0?net/Number(shares):0;return <section className="dash-card nav-calculator"><div className="card-heading"><h2>Valuation worksheet</h2><span className="tag">Your input values</span></div><form onSubmit={e=>{e.preventDefault();try{validateAmount(price);validateAmount(units);validateAmount(multiplier);validateAmount(shares);if(Number(liabilities)<0||net<=0)throw new Error('Net asset value must be positive after liabilities.');onSave(createRecord('nav',{name:'Portfolio valuation',asset:'Portfolio',amount:String(net),raw_units:units,price,multiplier,liabilities,shares,nav_per_share:String(perShare)}));setError('')}catch(e){setError((e as Error).message)}}}><div className="valuation-inputs">{[['Raw units',units,setUnits],['Reference price (USDG)',price,setPrice],['UI multiplier',multiplier,setMultiplier],['Liabilities (USDG)',liabilities,setLiabilities],['Total shares',shares,setShares]].map(([label,value,fn])=><label key={String(label)}>{String(label)}<input type="number" min={label==='Liabilities (USDG)'?'0':'0.000001'} step="any" required value={String(value)} onChange={e=>(fn as (s:string)=>void)(e.target.value)}/></label>)}</div><div className="valuation-result"><div><span>Net asset value</span><strong>{money(net)}</strong></div><div><span>NAV per share</span><strong>{money(perShare)}</strong></div><button className="secondary-btn" type="submit">Save valuation<Icon name="arrow"/></button></div><p className="small muted">Raw units × reference price × multiplier − liabilities. Values are calculated from your inputs; this worksheet does not create a cryptographic proof.</p>{error&&<p role="alert" className="form-error">{error}</p>}</form></section>}
function Settings({workspace,update,notify}:{workspace:Workspace;update:(w:Workspace)=>void;notify:(s:string)=>void}){const [name,setName]=useState(workspace.name);useEffect(()=>setName(workspace.name),[workspace.name]);return <div className="settings-grid"><section className="dash-card"><div className="card-heading"><h2>Workspace preferences</h2></div><form className="settings-form" onSubmit={e=>{e.preventDefault();if(name.trim()){update({...workspace,name:name.trim()});notify('Workspace preferences saved.')}}}><label>Workspace name<input value={name} maxLength={40} required onChange={e=>setName(e.target.value)}/></label><label className="checkbox-row"><input type="checkbox" checked={workspace.hideValues} onChange={e=>update({...workspace,hideValues:e.target.checked})}/><span>Hide amounts in overview and records</span></label><button className="primary-btn">Save preferences</button></form></section><section className="dash-card"><div className="card-heading"><h2>Your workspace data</h2></div><div className="settings-form"><p className="muted">Requests and preferences are saved in this browser. Keep an exported copy before clearing your browsing data.</p><button className="secondary-btn" onClick={()=>{download('cordon-workspace.json',JSON.stringify(workspace,null,2));notify('Workspace exported.')}}><Icon name="download"/>Export workspace</button><div className="settings-divider"/><h3>Network</h3><dl className="detail-list"><div><dt>Chain</dt><dd>Robinhood Chain</dd></div><div><dt>Chain ID</dt><dd>4663</dd></div><div><dt>Settlement unit</dt><dd>USDG</dd></div></dl><Link className="text-link" href="/docs">Protocol documentation ↗</Link></div></section></div>}

/** Testnet only: mint faucet Stock Tokens and USDG to the connected wallet. */
function TestFaucet({wallet,notify}:{wallet:string;notify:(s:string)=>void}){const [busy,setBusy]=useState('');async function mint(symbol:string){setBusy(symbol);try{const c=await import('@/lib/cordon');await c.faucet(symbol,wallet as `0x${string}`);notify(`Test ${symbol} sent to your wallet.`)}catch(e){notify((e as Error).message)}finally{setBusy('')}}return <section className="dash-card"><div className="card-heading"><h2>Testnet faucet</h2><span className="tag">Robinhood Chain Testnet</span></div><div className="settings-form"><p className="muted">Test Stock Tokens and USDG for trying Cordon. They have no value.</p><div className="form-actions" style={{borderTop:0,paddingTop:0,justifyContent:'flex-start',flexWrap:'wrap'}}>{['TSLA','NVDA','AMZN','USDG'].map(s=><button key={s} className="secondary-btn" disabled={!wallet||!!busy} onClick={()=>void mint(s)}>{busy===s?'Minting…':`Get test ${s}`}</button>)}</div>{!wallet&&<p className="small muted">Connect a wallet first.</p>}</div></section>}

type NoteAct='withdraw'|'claim'|'recombine'|'unlock';
const noteLabel:Record<NoteAct,string>={withdraw:'Withdraw',claim:'Claim income',recombine:'Recombine',unlock:'Unlock'};
const noteDone:Record<NoteAct,string>={withdraw:'Withdrawn to your wallet.',claim:'Income claimed. The payout is a new underlying note.',recombine:'Claims recombined into the underlying.',unlock:'Unlocked. The note is free again.'};
/** The workspace's private notes (never published) with the action each one allows. */
function PrivateNotes({notes,options,hide,busy,canAct,onAction,onSend,onInbox}:{notes:StoredNote[];options:AssetOption[];hide:boolean;busy:string;canAct:boolean;onAction:(n:StoredNote,a:NoteAct)=>void;onSend:(n:StoredNote)=>void;onInbox:()=>void}){const name=(a:string)=>options.find(o=>o.address&&BigInt(o.address).toString()===a)?.name??`0x${BigInt(a).toString(16).slice(0,6)}…`;const day=(ts:string)=>new Date(Number(ts)*1000).toLocaleDateString();
 return <section className="dash-card"><div className="card-heading"><h2>Private notes</h2><button className="secondary-btn" disabled={!canAct} onClick={onInbox}>Check inbox</button></div><div className="table-scroll"><table className="records-table"><thead><tr><th>Asset</th><th>Right</th><th>Raw units</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{notes.filter(n=>n.status!=='spent').map(n=>{const act:NoteAct|null=n.status!=='live'?null:n.lock!=='0'?'unlock':n.kind==='0'?'withdraw':n.kind==='2'?'claim':n.kind==='1'?'recombine':null;const note=n.lock!=='0'?'locked':n.termUntil!=='0'?`until ${day(n.termUntil)}`:n.termFrom!=='0'?`from ${day(n.termFrom)}`:'';
  return <tr key={n.commit}><td>{name(n.asset)}</td><td>{['UNDERLYING',...claimTypes][Number(n.kind)]}{note&&<small> · {note}</small>}</td><td className="mono">{hide?'••••':n.raw}</td><td><span className={'status-tag '+(n.status==='live'?'confirmed':'prepared')}>{n.status==='live'?'Live':'Pending'}</span></td><td style={{display:'flex',gap:8,flexWrap:'wrap'}}>{act&&<button className="secondary-btn" disabled={!canAct||!!busy} onClick={()=>onAction(n,act)}>{busy===n.commit?'Working…':noteLabel[act]}</button>}{n.status==='live'&&n.lock==='0'&&<button className="secondary-btn" disabled={!canAct||!!busy} onClick={()=>onSend(n)}>Send</button>}</td></tr>})}</tbody></table></div></section>}

const isCordonKey=(s?:string)=>/^0x[0-9a-f]{128}$/i.test((s??'').trim());
const isPledgeCode=(s?:string)=>/^0x[0-9a-f]{256}$/i.test((s??'').trim());
const kindName=(k:string)=>['UNDERLYING',...claimTypes][Number(k)]??'NOTE';
const assetName=(options:AssetOption[],a:string)=>options.find(o=>o.address&&BigInt(o.address).toString()===a)?.name??`0x${BigInt(a).toString(16).slice(0,6)}…`;

function SendModal({note,onClose,onSend}:{note:StoredNote;onClose:()=>void;onSend:(raw:string,to:string)=>void}){const [raw,setRaw]=useState(note.raw),[to,setTo]=useState(''),[error,setError]=useState('');
 return <Modal title="Send privately" onClose={onClose}><p className="muted">Moves {kindName(note.kind)} units to another Cordon key. Only the two of you see the note.</p><form className="request-form" onSubmit={e=>{e.preventDefault();if(!isCordonKey(to))return setError('Enter the recipient’s Cordon key (0x followed by 128 hex characters).');if(!/^\d+$/.test(raw)||BigInt(raw)<=0n||BigInt(raw)>BigInt(note.raw))return setError(`Enter 1 to ${note.raw} raw units.`);onSend(raw,to.trim())}}><label>Raw units<input value={raw} onChange={e=>setRaw(e.target.value.trim())} inputMode="numeric" required/></label><label>Recipient’s Cordon key<input value={to} onChange={e=>setTo(e.target.value)} placeholder="0x…" required/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Send<Icon name="arrow"/></button></div></form></Modal>}

/** Withdraw part or all of a free underlying note; the rest stays private as a new note. The whole note needs an explicit opt-in. */
function WithdrawModal({note,onClose,onWithdraw}:{note:StoredNote;onClose:()=>void;onWithdraw:(raw:string)=>void}){const [raw,setRaw]=useState(''),[error,setError]=useState(''),[linkOk,setLinkOk]=useState(false);const whole=/^\d+$/.test(raw)&&BigInt(raw)===BigInt(note.raw);
 return <Modal title="Withdraw to your wallet" onClose={onClose}><p className="muted">This note holds {note.raw} raw units. Whatever you leave stays private as a new note.</p><form className="request-form" onSubmit={e=>{e.preventDefault();if(!/^\d+$/.test(raw)||BigInt(raw)<=0n||BigInt(raw)>BigInt(note.raw))return setError(`Enter 1 to ${note.raw} raw units.`);if(whole&&!linkOk)return setError('Confirm the whole-note withdrawal, or withdraw a different amount.');onWithdraw(whole?'whole':raw)}}><label>Raw units<input value={raw} onChange={e=>{setRaw(e.target.value.trim());setError('')}} inputMode="numeric" placeholder={`1 to ${note.raw}`} aria-describedby={whole?'withdraw-link-hint':undefined} required/></label>{whole&&<p id="withdraw-link-hint" className="small muted">Withdrawing the exact deposited amount can link this withdrawal to your deposit. Withdraw a different amount to keep them unlinked.</p>}{whole&&<label className="small"><input type="checkbox" checked={linkOk} onChange={e=>{setLinkOk(e.target.checked);setError('')}}/> I understand; withdraw the whole note anyway</label>}{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn">Withdraw<Icon name="arrow"/></button></div></form></Modal>}

/** Encumbrances this wallet holds for others: release when the obligation is met, or request a default and enforce. */
function HeldCard({held,options,busy,canAct,onAction}:{held:HeldItem[];options:AssetOption[];busy:string;canAct:boolean;onAction:(x:HeldItem,a:'release'|'default'|'enforce')=>void}){
 return <section className="dash-card"><div className="card-heading"><h2>Held for you</h2><span className="tag">You are the holder</span></div><div className="table-scroll"><table className="records-table"><thead><tr><th>Asset</th><th>Claim</th><th>Raw units</th><th>Type · until</th><th>State</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{held.map(x=>{const e=JSON.parse(x.enc) as {kind:string;until:string};const st=x.state??'active';const btn=(a:'release'|'default'|'enforce',label:string)=><button className="secondary-btn" disabled={!canAct||!!busy} onClick={()=>onAction(x,a)}>{busy===x.enc?'Working…':label}</button>;
  return <tr key={x.enc}><td>{assetName(options,x.locked.asset)}</td><td>{kindName(x.locked.kind)}</td><td className="mono">{x.locked.raw}</td><td>{['LOCKUP','PLEDGE','LIEN'][Number(e.kind)]} · {new Date(Number(e.until)*1000).toLocaleDateString()}</td><td><span className={'status-tag '+(st==='active'?'prepared':st==='enforced'||st==='released'?'confirmed':'failed')}>{st}</span></td><td style={{display:'flex',gap:8,flexWrap:'wrap'}}>{(st==='active'||st==='defaulted')&&btn('release','Release')}{st==='active'&&btn('default','Request default')}{st==='defaulted'&&btn('enforce','Enforce')}</td></tr>})}</tbody></table></div></section>}

/** The key others use to send you notes, name you as a holder, or disclose to you. */
function CordonKeyCard({wallet,notify}:{wallet:string;notify:(s:string)=>void}){const [key,setKey]=useState('');const [code,setCode]=useState('');
 return <section className="dash-card"><div className="card-heading"><h2>Your Cordon key</h2><span className="tag">Safe to share</span></div><div className="settings-form"><p className="muted">Share it to receive notes, hold pledges and liens, or receive disclosures. It reveals nothing about your holdings.</p>{key?<><code style={{wordBreak:'break-all',fontSize:12}}>{key}</code><button className="secondary-btn" onClick={()=>{void navigator.clipboard?.writeText(key);notify('Cordon key copied.')}}>Copy</button></>:<button className="primary-btn" disabled={!wallet} onClick={()=>void import('@/lib/cordon').then(c=>c.cordonKey()).then(setKey).catch(e=>notify((e as Error).message))}>Show my Cordon key<Icon name="arrow"/></button>}{wallet&&<><p className="small muted">To hold a pledge or lien, give the borrower a fresh pledge code (one per pledge). Only you can ever release what is pledged with it.</p>{code?<><code style={{wordBreak:'break-all',fontSize:12}}>{code}</code><button className="secondary-btn" onClick={()=>{void navigator.clipboard?.writeText(code);notify('Pledge code copied.')}}>Copy pledge code</button></>:<button className="secondary-btn" onClick={()=>void import('@/lib/cordon').then(c=>c.pledgeCode()).then(setCode).catch(e=>notify((e as Error).message))}>New pledge code</button>}</>}{!wallet&&<p className="small muted">Connect a wallet first.</p>}</div></section>}

type Vault=Awaited<ReturnType<typeof import('@/lib/cordon')['vaultState']>>;
/** This wallet as a vault: request registration, then prove NAV over its free underlying notes each epoch. */
function VaultCard({wallet,notes,notify,signIn}:{wallet:string;notes:StoredNote[];notify:(s:string)=>void;signIn:()=>Promise<unknown>}){const [v,setV]=useState<Vault|null>(null),[shares,setShares]=useState('100'),[liab,setLiab]=useState('0'),[busy,setBusy]=useState('');
 const load=()=>{if(wallet)void import('@/lib/cordon').then(c=>c.vaultState(wallet as `0x${string}`)).then(setV).catch(()=>{})};useEffect(load,[wallet]);// eslint-disable-line react-hooks/exhaustive-deps
 async function run(f:(c:typeof import('@/lib/cordon'))=>Promise<string>){setBusy('x');try{notify(await f(await import('@/lib/cordon')));load()}catch(e){notify((e as Error).message)}finally{setBusy('')}}
 return <section className="dash-card"><div className="card-heading"><h2>Your vault</h2><span className="tag">{v?.registered?`Epoch ${v.epoch}`:v?.requested?'Awaiting governance':'Not registered'}</span></div><div className="settings-form">
 {!wallet?<p className="muted">Connect a wallet to manage a vault.</p>:!v?<p className="muted">Loading…</p>:!v.registered?<><p className="muted">{v.requested?'Registration is queued. Governance registers vaults through the 24-hour timelock; check back after that.':'Your free underlying notes become the vault’s holdings. Governance registers the vault through the 24-hour timelock.'}</p>{!v.requested&&<button className="primary-btn" disabled={!!busy} onClick={()=>void run(async c=>{if(!(await getAccessToken())){await signIn();if(!(await getAccessToken()))throw new Error('Sign in with your wallet (Sync workspace) to request a vault.')}await c.requestVault(wallet as `0x${string}`);return 'Registration requested.'})}>Request registration<Icon name="arrow"/></button>}</>:
 <><dl className="detail-list"><div><dt>Last NAV per share</dt><dd>{v.epoch?money(Number(v.navPerShare18)/1e18):'—'}</dd></div><div><dt>Last attested</dt><dd>{v.ts?new Date(v.ts*1000).toLocaleString():'Never'}</dd></div></dl><div className="form-row"><label>Total shares<input type="number" min="1" step="1" value={shares} onChange={e=>setShares(e.target.value)}/></label><label>Liabilities (USD)<input type="number" min="0" step="any" value={liab} onChange={e=>setLiab(e.target.value)}/></label></div><button className="primary-btn" disabled={!!busy} onClick={()=>void run(async c=>{const r=await c.attestNav({wallet:wallet as `0x${string}`,notes,shares:BigInt(Math.floor(Number(shares))),liabilitiesUsd:Number(liab)},{});return `Epoch ${r.epoch} attested: ${money(Number(r.navPerShare18)/1e18)} per share.`})}>{busy?'Proving…':'Prove and attest NAV'}<Icon name="arrow"/></button><p className="small muted">Values your free underlying notes at the latest oracle prices in a zero-knowledge proof; only NAV per share is published. One attestation per hour.</p></>}
 </div></section>}

type Opened=Awaited<ReturnType<typeof import('@/lib/cordon')['openDisclosure']>>;
/** Opens a disclosure link addressed to this wallet's Cordon key and checks each note on-chain. */
function DisclosureViewer({wallet,options}:{wallet:string;options:AssetOption[]}){const [id,setId]=useState(()=>typeof location==='undefined'?'':new URLSearchParams(location.search).get('view')??''),[d,setD]=useState<Opened|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function openIt(){setError('');setBusy(true);try{const g=id.trim().match(/[0-9a-f-]{36}/i)?.[0];if(!g)throw new Error('Paste a disclosure link or id.');setD(await (await import('@/lib/cordon')).openDisclosure(g))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="dash-card"><div className="card-heading"><h2>Open a disclosure</h2><span className="tag">Addressed to you</span></div><div className="settings-form"><div className="form-row"><label>Link or id<input value={id} onChange={e=>setId(e.target.value)} placeholder="https://usecordon.tech/dashboard/disclosure?view=…"/></label></div><button className="primary-btn" disabled={!wallet||busy} onClick={()=>void openIt()}>{busy?'Opening…':'Open and verify'}<Icon name="arrow"/></button>{!wallet&&<p className="small muted">Connect the wallet whose Cordon key it was shared with.</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 {d&&<><dl className="detail-list"><div><dt>Scope</dt><dd>{d.scope}</dd></div><div><dt>Purpose</dt><dd>{d.purpose}</dd></div><div><dt>Until</dt><dd>{d.until}</dd></div></dl><div className="table-scroll"><table className="records-table"><thead><tr><th>Asset</th><th>Right</th><th>Raw units</th><th>On-chain</th><th>Spent</th></tr></thead><tbody>{d.notes.map(n=><tr key={n.commit}><td>{assetName(options,n.asset)}</td><td>{kindName(n.kind)}</td><td className="mono">{n.raw}</td><td>{n.valid?'Verified':'Not found'}</td><td>{n.spent?'Spent':'Unspent'}</td></tr>)}</tbody></table></div><p className="small muted">“Verified” means the note matches a commitment in the pool. Spent status uses the nullifier the discloser supplied.</p></>}</div></section>}
