import Link from '@/components/compat/link';
import cordonBanner from '@/assets/cordon-banner-updated.png';

import {Brand,SocialLinks} from '@/components/cordon/shared';
const pages:Record<string,{title:string;lead:string;sections:{id:string;title:string;body:string;list?:string[]}[]}>= {
 docs:{title:'The Cordon protocol.',lead:'Confidential asset servicing for tokenized assets. Five modules, one shielded ledger.',sections:[
 {id:'architecture',title:'One ledger. Every servicing action.',body:'Cordon uses shielded notes for underlying assets, claims, encumbrances, and portfolio positions. Public verification establishes validity without publishing the owner’s holdings. Servicing actions are designed to pass through relayers, while scoped view keys support explicit disclosure.',list:['Rights bundles separate applicable functional claims from the underlying.','Encumbrances bind claims to obligations without transferring ownership.','Atomic DvP composes up to 16 settlement legs.','The corporate-action engine directs income to INCOME claims.','NAV attestations prove portfolio value at a defined epoch.']},
 {id:'claims',title:'Five claim types.',body:'An underlying note becomes a bundle of typed claims. Each applicable right can be held or transferred independently. Recombining the complete claim set recovers the underlying, provided no active encumbrance prevents it. A VOTE claim applies only where the underlying carries that right.',list:['PRINCIPAL — the underlying asset.','INCOME — the dividend stream, with an optional term.','VOTE — governance or consent rights, where supported.','REDEEM — the redemption or exit right.','CONTROL — authority to re-bundle.']},
 {id:'encumbrances',title:'Collateral with boundaries.',body:'A LOCKUP prevents transfer until its release time. A PLEDGE binds a claim to an obligation. A LIEN defines recourse and a recovery waterfall. A counterparty can verify that collateral exists and is locked without receiving a public view of the entire portfolio. Release conditions are explicit.'},
 {id:'settlement',title:'Atomic delivery versus payment.',body:'A trade can contain up to 16 legs, including assets, individual claims, and baskets. Every leg settles or none do. The protocol specifies sealed 60-second batches and reference-price guards. Stale or invalid marks defer settlement. An encumbered claim requires an authorized release before inclusion.'},
 {id:'income',title:'Income follows the INCOME claim.',body:'Corporate actions are accounted for at the claim level. The income index tracks multiplier-derived accrual. A time-bound income right can expire back into the bundle owner’s claim. Display values account for the underlying multiplier; amounts inside notes remain raw units.'},
 {id:'nav',title:'Provable value. Confidential composition.',body:'A NAV attestation proves the value of a vault or basket at an epoch while keeping its positions confidential. Valuation combines raw units, reference prices, and multipliers, then deducts liabilities. Investors can verify an attestation; authorized reviewers can receive a scoped view key. The workspace valuation worksheet calculates from your inputs and prepares a request for review.'},
 {id:'disclosure',title:'Disclosure is a deliberate choice.',body:'Access can be scoped to an individual claim, a bundle, or a portfolio. Preparing a disclosure records its recipient, purpose, scope, and expiry. View-key issuance is a separate authorized protocol action.'},
 {id:'fees',title:'Transparent servicing fees.',body:'The Cordon specification sets fees at 10 bps for bundling or unbundling, 5 bps per settlement leg, and 2 bps annually on encumbered value. NAV epochs use a flat fee. Fee allocation is 80% to the operators who run proving, relaying and registration, 10% to the treasury, 5% to $CRDN stakers, and 5% to buying back and burning $CRDN. Splitting a claim or setting an income term does not carry an additional protocol fee.'},
 {id:'workspace',title:'Your workspace.',body:'Create and review requests, organize bundles, compose settlement legs, calculate valuations, and export your records. Requests and preferences are stored on your device. A prepared request is separate from an authorized network transaction; no asset movement occurs when a request is saved.'}]},
 about:{title:'Behind the cordon.',lead:'The line between proving what matters and exposing everything.',sections:[{id:'purpose',title:'Asset rights deserve better tools.',body:'Tokenized assets carry more than principal. They carry income, redemption, control, and sometimes voting rights. Cordon brings these rights into a shared servicing model so they can be separated, pledged, recombined, and settled with confidentiality built in.'},{id:'people',title:'Built for the people managing assets.',body:'Funds and vault managers need verifiable NAV with confidential holdings. Lenders need collateral they can verify. Treasuries need independent control of their asset rights. Builders need reusable servicing primitives. These are the jobs Cordon is designed to support.'},{id:'principles',title:'Confidential. Provable. Disclosable.',body:'Confidential holdings do not have to mean unverifiable claims. Typed notes and proofs establish the rules; scoped disclosure gives authorized reviewers the visibility they need.'}]},
 privacy:{title:'Privacy at Cordon.',lead:'Your workspace. Your information. Your control.',sections:[{id:'device',title:'Workspace storage',body:'The workspace saves prepared requests and preferences in this browser’s local storage. These records can include asset names, amounts, recipients, obligations, and notes you enter. They remain available on this device until browser data is cleared. Use Export workspace to keep your own copy.'},{id:'wallet',title:'Wallet connection',body:'Connecting a browser wallet requests access to the account you select. The website does not request a seed phrase or private key. Connection does not initiate an asset transfer. You can disconnect the account from the workspace.'},{id:'exports',title:'Exports and disclosure',body:'Downloaded request and activity files contain the information you entered. Share exports only with intended recipients. Preparing a disclosure request does not itself share a view key or publish portfolio holdings.'},{id:'access',title:'Device access',body:'Anyone with access to this browser profile may be able to access the saved workspace. Hiding displayed values changes their presentation; it does not encrypt stored requests. Keep device and browser access appropriate for the information you enter.'}]},
 terms:{title:'Using Cordon.',lead:'Clear boundaries for your asset workspace.',sections:[{id:'workspace',title:'Prepared requests',body:'A request saved in the workspace is a record for review. It does not constitute a signed transaction, completed settlement, issued claim, verified NAV proof, or granted view key. Review each request before using it in a connected protocol workflow.'},{id:'inputs',title:'Your inputs',body:'You control the information entered into the workspace. Valuation calculations reflect those inputs and may differ from current market or oracle marks. Confirm asset identifiers, raw units, multipliers, recipients, and obligations before authorizing any action.'},{id:'rights',title:'Protocol conditions',body:'Asset eligibility and available claim types depend on the underlying asset. Encumbrances, screening, release conditions, and oracle guards apply to the corresponding protocol operations. A prepared request does not override those conditions.'},{id:'records',title:'Your records',body:'Workspace records are stored on your device. Export any records you need to retain before clearing browser data or moving to another device. Keep private keys and seed phrases out of request names, descriptions, and exports.'}]},
 cookies:{title:'Cookies & storage.',lead:'A focused workspace with clear local storage.',sections:[{id:'storage',title:'Essential workspace storage',body:'Cordon uses browser local storage to remember your workspace name, prepared requests, and display preferences. The data is used for the workspace features you choose. The frontend does not add advertising cookies or marketing trackers.'},{id:'control',title:'Your storage controls',body:'You can export workspace data from Settings. To remove saved requests and preferences from this device, clear this site’s data in your browser settings. Clearing local data removes the browser’s saved copy.'}]}
};
export function InfoPage({slug}:{slug:string}){const p=pages[slug];if(!p)return <div>Page not found</div>;return <div className="info-page"><header className="info-header"><Brand/><nav><Link href="/">Home</Link><Link href="/docs">Documentation</Link><Link href="/dashboard" className="primary-btn">Open app ↗</Link></nav></header><main className="info-body"><p className="eyebrow">CORDON / {slug.toUpperCase()}</p><h1>{p.title}</h1><p className="info-lead">{p.lead}</p>{slug==='about'&&<img className="info-banner" src={cordonBanner} alt="Cordon. Confidential asset servicing. Rights bundles, atomic settlement, provable NAV."/>}<nav className="info-toc" aria-label="On this page">{p.sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.title}</a>)}</nav>{p.sections.map(s=><section id={s.id} key={s.id} className="info-section"><h2>{s.title}</h2><p>{s.body}</p>{s.list&&<ul>{s.list.map(t=><li key={t}>{t}</li>)}</ul>}</section>)}<Link href="/dashboard" className="primary-btn">Open your workspace ↗</Link></main><footer className="info-footer"><Brand/><p>© 2026 Cordon. Confidential. Provable. Disclosable.</p><SocialLinks/></footer></div>}
