// Regenerates src/abis.ts from contracts/out (run after `forge build`): bun packages/shared/scripts/gen-abis.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const out = join(import.meta.dir, "../../../contracts/out");
const names = [
  "CordonPool",
  "BundleVerifier",
  "ActionEngine",
  "AssetGate",
  "CordonControl",
  "DvPSettler",
  "PriceOracle",
  "EncumbranceRegistry",
  "NavAttestor",
  "SolvencyVerifier",
  "CrdnStaking",
  "ScreeningGate",
];
let src = "// Generated by scripts/gen-abis.ts from contracts/out. Do not edit.\n";
for (const n of names) {
  const { abi } = JSON.parse(readFileSync(join(out, `${n}.sol`, `${n}.json`), "utf8"));
  const id = n === "DvPSettler" ? "dvpSettler" : n[0].toLowerCase() + n.slice(1);
  src += `\nexport const ${id}Abi = ${JSON.stringify(abi)} as const;\n`;
}
writeFileSync(join(import.meta.dir, "../src/abis.ts"), src);
// Edge functions (Deno) bundle only supabase/functions, so they get their own copy.
writeFileSync(join(import.meta.dir, "../../../supabase/functions/_shared/abis.ts"), src);
console.log(`wrote ${names.length} ABIs`);
